package reporter

import (
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"time"

	"github.com/rahul-aut-ind/go-analyzer/internal/analyzer"
	"github.com/rahul-aut-ind/go-analyzer/internal/engine"
)

// HTMLReporter writes analysis results as a self-contained HTML file with
// inline CSS and vanilla-JS filtering. No CDN or external dependencies.
type HTMLReporter struct {
	// TargetDir is the Go module directory that was analyzed.
	TargetDir string
}

// severityGroup holds findings for a single severity level.
type severityGroup struct {
	Severity string
	Count    int
	Findings []analyzer.Finding
}

// htmlData is the template context for the HTML report.
type htmlData struct {
	ProjectName    string
	GeneratedAt    string
	TargetDir      string
	Duration       string
	Total          int
	Critical       int
	High           int
	Medium         int
	Low            int
	Info           int
	SeverityGroups []severityGroup
	Errors         map[string]string
}

const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<!--
  Generated by go-analyzer
  https://github.com/rahul-aut-ind/go-analyzer
  MIT License
-->
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Scan Report — {{.ProjectName}}</title>
<style>
:root{
  --bg:#0f172a;
  --panel:#111827;
  --card:#1f2933;
  --text:#e5e7eb;
  --muted:#9ca3af;
  --border:#374151;
}
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:system-ui,sans-serif;background:var(--bg);color:var(--text);padding:24px}
h1{font-size:1.8rem;margin-bottom:6px}
.meta{font-size:.85rem;color:var(--muted);margin-bottom:20px}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:14px;margin-bottom:24px}
.card{background:var(--card);border-radius:12px;padding:16px;box-shadow:0 2px 6px rgba(0,0,0,.3);transition:.2s}
.card:hover{transform:translateY(-2px)}
.card .num{font-size:1.8rem;font-weight:700}
.card .label{font-size:.75rem;text-transform:uppercase;color:var(--muted)}
.critical .num{color:#ef4444}
.high .num{color:#f97316}
.medium .num{color:#facc15}
.low .num{color:#3b82f6}
.info .num{color:#9ca3af}
.filters{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:16px}
select,input{padding:8px;border-radius:6px;border:1px solid var(--border);background:#020617;color:var(--text)}
.table-wrap{max-height:calc(100vh - 320px);overflow-y:auto;border-radius:10px}
table{width:100%;border-collapse:collapse;background:var(--panel)}
thead th{position:sticky;top:0;z-index:2;background:#020617;text-transform:uppercase;color:var(--muted);padding:10px;font-size:.85rem}
td{padding:10px;font-size:.85rem;border-bottom:1px solid var(--border)}
tr:hover td{background:#1e293b}
.sev{padding:3px 8px;border-radius:4px;font-size:.7rem;font-weight:600}
.sev-critical{background:#7f1d1d;color:#fecaca}
.sev-high{background:#7c2d12;color:#fed7aa}
.sev-medium{background:#78350f;color:#fde68a}
.sev-low{background:#1e3a8a;color:#bfdbfe}
.sev-info{background:#374151;color:#d1d5db}
.suggestion{color:var(--muted);font-style:italic}
.hidden{display:none}
</style>
</head>
<body>
<h1>{{.ProjectName}} — Scan Report</h1>
<div class="meta">
  Scanned On: {{.GeneratedAt}} | Target: <code>{{.TargetDir}}</code> | Duration: {{.Duration}}
</div>

<div class="cards">
  <div class="card"><div class="num">{{.Total}}</div><div class="label">Total</div></div>
  <div class="card critical"><div class="num">{{.Critical}}</div><div class="label">Critical</div></div>
  <div class="card high"><div class="num">{{.High}}</div><div class="label">High</div></div>
  <div class="card medium"><div class="num">{{.Medium}}</div><div class="label">Medium</div></div>
  <div class="card low"><div class="num">{{.Low}}</div><div class="label">Low</div></div>
  <div class="card info"><div class="num">{{.Info}}</div><div class="label">Info</div></div>
</div>

<div class="filters">
  <select id="sev" onchange="filter()">
    <option value="">All Severities</option>
    <option value="critical">Critical</option>
    <option value="high">High</option>
    <option value="medium">Medium</option>
    <option value="low">Low</option>
    <option value="info">Info</option>
  </select>
  <input id="rule" placeholder="Rule ID" oninput="filter()">
  <input id="file" placeholder="File" oninput="filter()">
</div>

<div class="table-wrap">
<table id="tbl">
<thead><tr>
<th>Rule</th><th>Severity</th><th>File</th><th>Line</th><th>Message</th><th>Suggestion</th>
</tr></thead>
{{range .SeverityGroups}}
<tbody class="grp grp-{{.Severity}}" id="grp-{{.Severity}}">
<tr class="grp-hdr" onclick="toggleGrp('{{.Severity}}')">
  <td colspan="6" style="cursor:pointer;font-weight:600;background:#1e293b;user-select:none">
    <span id="arrow-{{.Severity}}">▼</span>
    <span class="sev sev-{{.Severity}}">{{.Severity}}</span>
    <span style="color:var(--muted);font-size:.8rem"> {{.Count}} findings</span>
  </td>
</tr>
{{range .Findings}}
<tr class="finding-row" data-s="{{.Severity}}" data-r="{{.RuleID}}" data-f="{{.File}}">
  <td><code>{{.RuleID}}</code></td>
  <td><span class="sev sev-{{.Severity}}">{{.Severity}}</span></td>
  <td title="{{.File}}"><code>{{.File}}</code></td>
  <td>{{.Line}}</td>
  <td>{{.Message}}</td>
  <td class="suggestion">{{if .Suggestion}}{{.Suggestion}}{{else}}-{{end}}</td>
</tr>
{{end}}
</tbody>
{{end}}
</table>
</div>

<script>
function toggleGrp(sev){
  const rows=document.querySelectorAll('#grp-'+sev+' .finding-row');
  const arrow=document.getElementById('arrow-'+sev);
  const hidden=rows.length>0&&rows[0].classList.contains('hidden');
  rows.forEach(r=>r.classList.toggle('hidden',!hidden));
  arrow.textContent=hidden?'▼':'▶';
}
function filter(){
 const s=document.getElementById('sev').value;
 const r=document.getElementById('rule').value.toLowerCase();
 const f=document.getElementById('file').value.toLowerCase();
 document.querySelectorAll('#tbl .finding-row').forEach(row=>{
  const ok = (!s||row.dataset.s===s) &&
             (!r||row.dataset.r.toLowerCase().includes(r)) &&
             (!f||row.dataset.f.toLowerCase().includes(f));
  row.classList.toggle('hidden',!ok);
 });
}
</script>
<div style="display:none" aria-hidden="true" data-generator="go-analyzer" data-project="https://github.com/rahul-aut-ind/go-analyzer" data-license="MIT"></div>
</body>
</html>
`

// Write serialises result to <outputDir>/report-<timestamp>.html and returns
// the absolute path of the created file.
func (r *HTMLReporter) Write(result *engine.RunResult, outputDir string) (string, error) {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return "", fmt.Errorf("creating output dir %s: %w", outputDir, err)
	}

	counts := map[string]int{"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
	for _, f := range result.Findings {
		counts[f.Severity]++
	}

	errStrs := make(map[string]string, len(result.Errors))
	for k, v := range result.Errors {
		errStrs[k] = v.Error()
	}

	projectName := filepath.Base(r.TargetDir)
	if projectName == "" || projectName == "." {
		projectName = "go-analyzer"
	}

	data := htmlData{
		ProjectName: projectName,
		GeneratedAt: time.Now().UTC().Format("02 Jan 2006, 15:04 UTC"),
		TargetDir:   r.TargetDir,
		Duration:    formatDuration(result.Duration),
		Total:       len(result.Findings),
		Critical:    counts["critical"],
		High:        counts["high"],
		Medium:      counts["medium"],
		Low:         counts["low"],
		Info:        counts["info"],
		Errors:      errStrs,
	}

	severities := []string{"critical", "high", "medium", "low", "info"}
	for _, sev := range severities {
		var group []analyzer.Finding
		for _, f := range result.Findings {
			if f.Severity == sev {
				group = append(group, f)
			}
		}
		if len(group) > 0 {
			data.SeverityGroups = append(data.SeverityGroups, severityGroup{
				Severity: sev,
				Count:    len(group),
				Findings: group,
			})
		}
	}

	tmpl, err := template.New("report").Parse(htmlTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing HTML template: %w", err)
	}

	ts := time.Now().UTC().Format("20060102-150405")
	outPath := filepath.Join(outputDir, fmt.Sprintf("report-%s.html", ts))

	f, err := os.Create(outPath)
	if err != nil {
		return "", fmt.Errorf("creating HTML report file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return "", fmt.Errorf("rendering HTML template: %w", err)
	}

	return outPath, nil
}
