version: 2

project_name: go-analyzer

before:
  hooks:
    - go mod tidy

builds:
  - id: go-analyzer
    main: .
    binary: go-analyzer
    ldflags:
      - -X github.com/rahul-aut-ind/go-analyzer/cmd.version={{.Version}}
      - -X github.com/rahul-aut-ind/go-analyzer/cmd.commit={{.Commit}}
      - -X github.com/rahul-aut-ind/go-analyzer/cmd.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Documentation
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: Maintenance
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 3
    - title: Other
      order: 999
  filters:
    exclude:
      - "^Merge pull request"
      - "^Merge branch"

release:
  github:
    owner: rahul-aut-ind
    name: go-analyzer
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
