// Package config provides configuration loading for go-analyzer via Viper.
// It reads a .goanalyzer.yaml file from the working directory (or a specified
// path) and applies sensible defaults for any missing keys.
package config

import (
	"fmt"
	"os"

	"github.com/spf13/viper"
)

// Config holds all tunable settings for go-analyzer.
type Config struct {
	// Scan holds settings that control which files/directories to include.
	Scan struct {
		// Exclude is a list of path patterns to skip during analysis.
		Exclude []string
	}
	// Thresholds controls numeric limits used by analysis modules.
	Thresholds struct {
		// CyclomaticComplexity is the maximum acceptable cyclomatic complexity per function.
		CyclomaticComplexity int
		// FunctionLength is the maximum acceptable function body line count.
		FunctionLength int
		// CoverageMinimum is the minimum acceptable test coverage percentage (0–100).
		CoverageMinimum float64
	}
	// Rules controls which rule IDs are active.
	Rules struct {
		// Disable is a list of rule IDs to suppress.
		Disable []string
	}
	// Dependencies holds dependency-check policy settings.
	Dependencies struct {
		LicensePolicy struct {
			// Deny is a list of SPDX license identifiers that are not allowed.
			Deny []string
		}
	}
	// Report controls output file generation.
	Report struct {
		// OutputDir is the directory where reports are written.
		OutputDir string
		// Formats is the list of report formats to generate (json, markdown, html).
		Formats []string
		// HistoryLimit is the number of historical coverage snapshots to retain.
		HistoryLimit int
	}
}

// Load reads the config file at path (or searches for .goanalyzer.yaml in the
// current directory when path is empty) and returns a populated Config struct
// with defaults applied for any missing keys.
func Load(path string) (*Config, error) {
	v := viper.New()
	applyDefaults(v)

	if path != "" {
		v.SetConfigFile(path)
	} else {
		v.SetConfigName(".goanalyzer")
		v.SetConfigType("yaml")
		v.AddConfigPath(".")
	}

	if err := v.ReadInConfig(); err != nil {
		// Config file not found is acceptable — we just use defaults.
		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
			// Check if it's a "file not found" OS error for explicit paths.
			if !os.IsNotExist(err) {
				return nil, fmt.Errorf("reading config: %w", err)
			}
		}
	}

	cfg := &Config{}
	if err := v.Unmarshal(cfg); err != nil {
		return nil, fmt.Errorf("unmarshalling config: %w", err)
	}

	return cfg, nil
}

// WriteDefault creates a .goanalyzer.yaml at dest with all default values.
func WriteDefault(dest string) error {
	const defaultYAML = `# go-analyzer configuration file
# Generated by: go-analyzer init

scan:
  exclude: []

thresholds:
  cyclomaticComplexity: 10
  functionLength: 50
  coverageMinimum: 80.0

rules:
  disable: []

dependencies:
  licensePolicy:
    deny: []

report:
  outputDir: .goanalyzer/reports
  formats:
    - html
    - markdown
  historyLimit: 5
`
	if _, err := os.Stat(dest); err == nil {
		return fmt.Errorf("%s already exists", dest)
	}
	return os.WriteFile(dest, []byte(defaultYAML), 0o644)
}

// applyDefaults sets Viper defaults so that missing keys in the YAML file still
// produce a usable Config struct.
func applyDefaults(v *viper.Viper) {
	v.SetDefault("thresholds.cyclomaticComplexity", 10)
	v.SetDefault("thresholds.functionLength", 50)
	v.SetDefault("thresholds.coverageMinimum", 80.0)
	v.SetDefault("report.outputDir", "goanalyzer/reports")
	v.SetDefault("report.formats", []string{"html", "markdown"})
	v.SetDefault("report.historyLimit", 5)
}
